### ISSUE TITLE
Proof of concept journey for one geographic area

### ISSUE THREAD

**Issue by livcheerful** [livcheerful/anywhereadventures#1]
### Dependencies

- [ ] https://github.com/livcheerful/anywhereadventures/issues/3
- [ ] https://github.com/livcheerful/anywhereadventures/issues/7
- [ ] #8
- [ ] #9
- [ ] #10

### About
**Requirements**:
- Can be delivered as wireframes or as a video demonstration
- Includes LC content + considers accessibility

### TODOs
- [ ] Generate video / wireframes
- [ ] Gather feedback before final submission

### Questions
- [x] Is it okay to use Seattle as a draft location (apart from the three other selected locations)? It could be good for future on-site testing
