### ISSUE TITLE
Develop content plan for location scouting campaign

### ISSUE THREAD

**Issue by livcheerful** [livcheerful/anywhereadventures#12]
### Dependencies
- [ ] #14

### Parent task

*Is this task part of a larger deliverable?*
- [x] #5 

### About
Goals for campaign:

- LC learns more about how to engage local and Gen Z audiences
- Members of the public learn more about the local history of AA sites
- Non-local audiences are inspired to look up items on loc.gov of their home towns

### TODOs
- [ ] Plan what videos needs to be made to promote it
- [ ] Decide what are requirements for submission
- [ ] How will we collect submissions? Through a hashtag? A form? etc

### Questions
*What needs to be answered to progress on this task?*
- What will factor in to choosing locations?
- Should we make a landing page for the website before release so people can learn about the project? 
- When will this happen? (will happen between Jan - Mar)

Before launching the campaign, we should have:
- #10  real designs + activity pairings so people can understand the project
- Posted a couple of vides
