### ISSUE TITLE
Brainstorm different styles of videos that could be made

### ISSUE THREAD

**Issue by livcheerful** [livcheerful/anywhereadventures#13]
### Parent task

*Is this task part of a larger deliverable?*
- [x] https://github.com/livcheerful/anywhereadventures/issues/5

### About
Come up with overarching "styles" of content that could be made. (For example, a storytelling one, a funny one, a promotional one).

A good thing to keep in mind: 
- try to provide some kind of value to the viewer: something super informational that they can learn from
- maybe encourage rewatching
- encourage sharing to friends (if something is funny, educational, or cool)

### TODOs
- [x] Create Figma page to collect ideas: https://www.figma.com/board/EWa1n7kS6PsXx8oXV15JVD/Anywhere-Adventures-Brainstorm-Board?node-id=1-6542&t=I3ofSf6zc0vPflAj-4
- [ ] Look at other channels for inspiration for conetnt
