### ISSUE TITLE
Brainstorm activities

### ISSUE THREAD

**Issue by livcheerful** [livcheerful/anywhereadventures#3]
## Link to Figma for brainstorming:
https://www.figma.com/board/EWa1n7kS6PsXx8oXV15JVD/Anywhere-Adventures-Brainstorm-Board?node-id=1-6665&t=I3ofSf6zc0vPflAj-4

### Parent task
- [x] https://github.com/livcheerful/anywhereadventures/issues/1 

### About

Come up with ALL the different kinds of activities, features, and fun things that the website could include.

<img width="704" alt="image" src="https://github.com/user-attachments/assets/63172b7d-5216-499f-a706-163840cc689e">

### TODOs
- [x] Start a Figma to collect ideas: https://www.figma.com/board/EWa1n7kS6PsXx8oXV15JVD/Anywhere-Adventures-Brainstorm-Board?node-id=1-6665&t=I3ofSf6zc0vPflAj-4
- [ ] Explore collections for inspiration
- [ ] Think of activity part, zine customization part, and sharing part

### Questions
- [ ] Who should be involved in this? Would other people be interested in brainstorming too?
