### ISSUE TITLE
First draft of activities + overall site flow

### ISSUE THREAD

**Issue by livcheerful** [livcheerful/anywhereadventures#7]
### Dependencies

*What other tasks need to get done before this can be done*
- [x] https://github.com/livcheerful/anywhereadventures/issues/3

### Parent task

*Is this task part of a larger deliverable?*
- [x] https://github.com/livcheerful/anywhereadventures/issues/1 

### About

Refined drafts / wireframes / drawings that can communicate the activities enough for user testing. A more realistic view of translating brainstorming into actual experiences

### TODOs
- [ ] Three journeys of different kinds with Location, LOC Item, Activity, and output zine
- [ ] Include outputs for each activity + how it would tie into overall zine creation
- [ ] Draft how users move between explore -> create -> share
- [ ] Think of user story of navigating to locations, deciding to use the website, how will they find out what they're signing up for, what things they'll need, etc
